[package]
name = "dkg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto = {path = "../crypto"}
tokio = {version = "1", features = ["full"]}
